import { supabase } from './supabase'

export async function fetchBookingPayment(bookingId) {
  const { data, error } = await supabase
    .from('bookings')
    .select('id, customer_name, total_amount, payment_status, payment_method, payment_link, payment_requested_amount, payment_screenshot_url')
    .eq('id', bookingId)
    .single()
  if (error) throw error
  return data
}

/**
 * Turns a saved UPI deep-link (upi://...) into a scannable QR image, using
 * the same public QR image renderer the admin panel uses — no API key
 * needed. The deep-link itself was generated by the admin at request time
 * and is stored on the booking, so the customer page never needs the raw
 * UPI ID/payee name directly.
 */
export function upiLinkToQrImageUrl(upiLink) {
  return `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(upiLink)}`
}

/** Uploads proof-of-payment screenshot and marks the booking as awaiting confirmation. */
export async function uploadPaymentScreenshot(bookingId, file) {
  const path = `${bookingId}/${Date.now()}-${file.name}`
  const { error: uploadError } = await supabase.storage.from('payment-proofs').upload(path, file, { upsert: true })
  if (uploadError) throw uploadError
  const { data } = supabase.storage.from('payment-proofs').getPublicUrl(path)
  const { error } = await supabase
    .from('bookings')
    .update({ payment_screenshot_url: data.publicUrl, payment_status: 'screenshot_uploaded' })
    .eq('id', bookingId)
  if (error) throw error
  return data.publicUrl
}
