// Kept separate from src/lib/i18n.jsx on purpose: the assistant only
// ever needs these three languages regardless of which of the site's 6
// languages is currently selected, and keeping it isolated means a typo
// here can't break the main translation file.
export const ASSISTANT_LANGS = [
  { code: 'en', label: 'English', speech: 'en-IN' },
  { code: 'hi', label: 'हिंदी', speech: 'hi-IN' },
  { code: 'or', label: 'ଓଡ଼ିଆ', speech: null }, // no browser speech support — guided text only
]

export const ASSISTANT_STRINGS = {
  en: {
    promptTitle: 'Are you a senior citizen, or would you like some help booking?',
    promptBody: 'We can guide you step by step, and even book using your voice.',
    yes: 'Yes, please help me',
    no: 'No, I\'m fine',
    chooseLanguage: 'Choose your language',
    exitAssistant: 'Exit guided mode',
    tapToSpeak: 'Tap and speak',
    listening: 'Listening…',
    typeInstead: 'Type your answer instead',
    heardYou: 'I heard: ',
    isThisRight: 'Is this correct?',
    yesConfirm: 'Yes, correct',
    noTryAgain: 'No, try again',
    next: 'Next',
    stepPatient: 'Let\'s start. Please tell me the patient\'s full name.',
    stepAge: 'What is the patient\'s age?',
    stepGender: 'Is the patient male, female, or other?',
    stepBloodGroup: 'What is the patient\'s blood group? If you don\'t know, choose Unknown.',
    stepTests: 'Which test or health package would you like? For example, say "full body checkup" or a test name.',
    stepTestsNotFound: 'I couldn\'t find that test. Please try saying it again, or type to search.',
    stepType: 'Would you like to visit our lab, or should we collect the sample from your home?',
    optionLab: 'Visit lab',
    optionHome: 'Home collection',
    stepLocation: 'Please share your home address, or use the map to pick your location.',
    stepSchedule: 'Which date would you like? You can say "today", "tomorrow", or a date.',
    stepContactName: 'Now, whose name should we put as the contact for this booking?',
    stepPhone: 'Please tell me a phone number we can contact you on.',
    stepReview: 'Here is your booking. Please check everything is correct, then tap Confirm.',
    stepPayment: 'Please pay the amount shown, then upload a screenshot of the payment to continue.',
    bookingDone: 'Your booking is confirmed. Please save a screenshot of this page. Our team will call you soon to confirm the time.',
    confirm: 'Confirm booking',
    installAppTitle: 'Add Plasma Care to your home screen?',
    installAppBody: 'So next time you can book directly, without opening the browser again.',
    installApp: 'Add to home screen',
    notNow: 'Not now',
  },
  hi: {
    promptTitle: 'क्या आप वरिष्ठ नागरिक हैं, या बुकिंग में मदद चाहिए?',
    promptBody: 'हम आपको हर कदम पर मदद करेंगे, और आप बोलकर भी बुकिंग कर सकते हैं।',
    yes: 'हाँ, मदद चाहिए',
    no: 'नहीं, मैं ठीक हूँ',
    chooseLanguage: 'अपनी भाषा चुनें',
    exitAssistant: 'गाइड मोड बंद करें',
    tapToSpeak: 'दबाएं और बोलें',
    listening: 'सुन रहा हूँ…',
    typeInstead: 'इसके बजाय टाइप करें',
    heardYou: 'मैंने सुना: ',
    isThisRight: 'क्या यह सही है?',
    yesConfirm: 'हाँ, सही है',
    noTryAgain: 'नहीं, फिर से बोलें',
    next: 'आगे',
    stepPatient: 'शुरू करते हैं। कृपया मरीज़ का पूरा नाम बताएं।',
    stepAge: 'मरीज़ की उम्र क्या है?',
    stepGender: 'मरीज़ पुरुष हैं, महिला हैं, या अन्य?',
    stepBloodGroup: 'मरीज़ का ब्लड ग्रुप क्या है? अगर पता नहीं है तो "पता नहीं" चुनें।',
    stepTests: 'आपको कौन सा टेस्ट या हेल्थ पैकेज चाहिए? जैसे "फुल बॉडी चेकअप" या टेस्ट का नाम बोलें।',
    stepTestsNotFound: 'मुझे वह टेस्ट नहीं मिला। कृपया फिर से बोलें, या टाइप करके खोजें।',
    stepType: 'क्या आप हमारी लैब आएंगे, या हम आपके घर से सैंपल लें?',
    optionLab: 'लैब जाएंगे',
    optionHome: 'घर से सैंपल',
    stepLocation: 'कृपया अपना पता बताएं, या मैप पर जगह चुनें।',
    stepSchedule: 'कौन सी तारीख चाहिए? आप "आज", "कल", या तारीख बोल सकते हैं।',
    stepContactName: 'अब, बुकिंग के लिए संपर्क नाम क्या रखें?',
    stepPhone: 'कृपया एक फ़ोन नंबर बताएं जिस पर हम संपर्क कर सकें।',
    stepReview: 'यह रही आपकी बुकिंग। कृपया जांच लें, फिर Confirm दबाएं।',
    stepPayment: 'कृपया दिखाई गई रकम का भुगतान करें, फिर आगे बढ़ने के लिए पेमेंट का स्क्रीनशॉट अपलोड करें।',
    bookingDone: 'आपकी बुकिंग पक्की हो गई है। कृपया इस पेज का स्क्रीनशॉट सेव कर लें। हमारी टीम समय पक्का करने के लिए जल्दी आपको फ़ोन करेगी।',
    confirm: 'बुकिंग पक्की करें',
    installAppTitle: 'Plasma Care को अपनी होम स्क्रीन पर जोड़ें?',
    installAppBody: 'ताकि अगली बार आप सीधे बुकिंग कर सकें, ब्राउज़र खोले बिना।',
    installApp: 'होम स्क्रीन पर जोड़ें',
    notNow: 'अभी नहीं',
  },
  or: {
    promptTitle: 'ଆପଣ ଜଣେ ବରିଷ୍ଠ ନାଗରିକ କି, କିମ୍ବା ବୁକିଂରେ ସାହାଯ୍ୟ ଦରକାର?',
    promptBody: 'ଆମେ ଆପଣଙ୍କୁ ପାଦେ ପାଦେ ସାହାଯ୍ୟ କରିବୁ।',
    yes: 'ହଁ, ସାହାଯ୍ୟ ଦରକାର',
    no: 'ନା, ମୁଁ ଠିକ୍ ଅଛି',
    chooseLanguage: 'ଆପଣଙ୍କର ଭାଷା ବାଛନ୍ତୁ',
    exitAssistant: 'ଗାଇଡ୍ ମୋଡ୍ ବନ୍ଦ କରନ୍ତୁ',
    tapToSpeak: 'ଦବାନ୍ତୁ ଏବଂ କୁହନ୍ତୁ',
    listening: 'ଶୁଣୁଛି…',
    typeInstead: 'ଏହା ବଦଳରେ ଟାଇପ୍ କରନ୍ତୁ',
    heardYou: 'ମୁଁ ଶୁଣିଲି: ',
    isThisRight: 'ଏହା ଠିକ୍ କି?',
    yesConfirm: 'ହଁ, ଠିକ୍ ଅଛି',
    noTryAgain: 'ନା, ପୁଣି କୁହନ୍ତୁ',
    next: 'ପରବର୍ତ୍ତୀ',
    stepPatient: 'ଆରମ୍ଭ କରିବା। ରୋଗୀଙ୍କର ପୁରା ନାମ ଟାଇପ୍ କରନ୍ତୁ।',
    stepAge: 'ରୋଗୀଙ୍କର ବୟସ କେତେ?',
    stepGender: 'ରୋଗୀ ପୁରୁଷ, ମହିଳା, ନା ଅନ୍ୟ?',
    stepBloodGroup: 'ରୋଗୀଙ୍କର ବ୍ଲଡ୍ ଗ୍ରୁପ୍ କ\'ଣ? ଜଣା ନଥିଲେ "ଜଣା ନାହିଁ" ବାଛନ୍ତୁ।',
    stepTests: 'ଆପଣଙ୍କୁ କେଉଁ ଟେଷ୍ଟ କିମ୍ବା ହେଲ୍ଥ ପ୍ୟାକେଜ୍ ଦରକାର? ଟାଇପ୍ କରି ଖୋଜନ୍ତୁ।',
    stepTestsNotFound: 'ମୋତେ ସେହି ଟେଷ୍ଟ ମିଳିଲା ନାହିଁ। ଦୟାକରି ପୁଣି ଟାଇପ୍ କରନ୍ତୁ।',
    stepType: 'ଆପଣ ଆମର ଲାବ୍‌କୁ ଆସିବେ, ନା ଆମେ ଆପଣଙ୍କ ଘରୁ ସାମ୍ପଲ୍ ନେବୁ?',
    optionLab: 'ଲାବ୍‌କୁ ଯିବେ',
    optionHome: 'ଘର ସଂଗ୍ରହ',
    stepLocation: 'ଦୟାକରି ଆପଣଙ୍କ ଠିକଣା ଦିଅନ୍ତୁ, କିମ୍ବା ମାନଚିତ୍ରରେ ସ୍ଥାନ ବାଛନ୍ତୁ।',
    stepSchedule: 'କେଉଁ ତାରିଖ ଦରକାର? ଟାଇପ୍ କରନ୍ତୁ।',
    stepContactName: 'ବର୍ତ୍ତମାନ, ବୁକିଂ ପାଇଁ ଯୋଗାଯୋଗ ନାମ କ\'ଣ ଦେବେ?',
    stepPhone: 'ଦୟାକରି ଏକ ଫୋନ୍ ନମ୍ବର ଦିଅନ୍ତୁ ଯାହାରେ ଆମେ ଯୋଗାଯୋଗ କରିପାରିବୁ।',
    stepReview: 'ଏଠାରେ ଆପଣଙ୍କର ବୁକିଂ ଅଛି। ଯାଞ୍ଚ କରି Confirm ଦବାନ୍ତୁ।',
    stepPayment: 'ଦୟାକରି ଦେଖାଯାଇଥିବା ଟଙ୍କା ଦିଅନ୍ତୁ, ତା\'ପରେ ପେମେଣ୍ଟର ସ୍କ୍ରିନସଟ୍ ଅପଲୋଡ୍ କରନ୍ତୁ।',
    bookingDone: 'ଆପଣଙ୍କର ବୁକିଂ ନିଶ୍ଚିତ ହୋଇଛି। ଦୟାକରି ଏହି ପୃଷ୍ଠାର ସ୍କ୍ରିନସଟ୍ ସେଭ୍ କରନ୍ତୁ। ଆମ ଟିମ୍ ସମୟ ନିଶ୍ଚିତ କରିବାକୁ ଶୀଘ୍ର ଆପଣଙ୍କୁ ଫୋନ୍ କରିବେ।',
    confirm: 'ବୁକିଂ ନିଶ୍ଚିତ କରନ୍ତୁ',
    installAppTitle: 'Plasma Care କୁ ଆପଣଙ୍କ ହୋମ୍ ସ୍କ୍ରିନ୍‌ରେ ଯୋଡ଼ନ୍ତୁ?',
    installAppBody: 'ଯାହା ଫଳରେ ପରବର୍ତ୍ତୀ ଥର ସିଧାସଳଖ ବୁକ୍ କରିପାରିବେ।',
    installApp: 'ହୋମ୍ ସ୍କ୍ରିନ୍‌ରେ ଯୋଡ଼ନ୍ତୁ',
    notNow: 'ବର୍ତ୍ତମାନ ନୁହେଁ',
  },
}
