-- Auto-generated from MRP_PRICE_LIST.pdf. Run once in the Supabase SQL editor.
-- Inserts the full 220-test catalog. Skips any test whose name already exists,
-- so this is safe to re-run without creating duplicates.

insert into individual_tests (name, category, price, is_active)
select v.name, v.category, v.price, true
from (values
  ('25 Hydroxy (OH) Vitamin D', 'Serum', 1200.00),
  ('Absolute Eosinophil Count (AEC)', 'EDTA Whole Blood', 100.00),
  ('Activated Partial Thromboplastin Time (APTT)', 'Citrated Plasma', 480.00),
  ('Alanine Aminotransferase (ALT/SGPT)', 'Serum', 150.00),
  ('Anti-Cyclic Citrullinated Peptide (Anti-CCP)', 'Serum', 1200.00),
  ('Anti-Streptolysin O (ASO- Titer)', 'Serum', 500.00),
  ('Anti-Thyroid Peroxidase (Anti TPO)', 'Serum', 1300.00),
  ('Aspartate Aminotransferase (AST/SGOT)', 'Serum', 150.00),
  ('Beta Human Chorionic Gonadotropin (Beta-HCG)', 'Serum', 600.00),
  ('Bilirubin Total, Direct & Indirect', 'Serum', 200.00),
  ('Bleeding Time & Clotting Time (BT&CT)', 'Fresh Whole Blood', 150.00),
  ('Blood Group & Rh Type', 'EDTA Whole Blood', 150.00),
  ('C- Peptide (Fasting)', 'Serum', 1000.00),
  ('C- Peptide (Post Prandial)', 'Serum', 1000.00),
  ('C-Reactive Protein (CRP- Quantitative)', 'Serum', 450.00),
  ('Complete Hemogram Test (CBC)', 'EDTA Whole Blood', 300.00),
  ('Dengue IgG IgM NS1 (Rapid)', 'Serum', 800.00),
  ('Erythrocyte Sedimentation Rate (ESR-Westergren)', 'EDTA Whole Blood/ Sodium Citrate 3.8%', 120.00),
  ('Ferritin', 'Serum', 800.00),
  ('Follicle Stimulating Hormone (FSH)', 'Serum', 500.00),
  ('Free Thyroid Function Test (FTFT)', 'Serum', 700.00),
  ('Free Thyroxine (FT4)', 'Serum', 300.00),
  ('Free Triiodothyronine (FT3)', 'Serum', 300.00),
  ('Glucose (Fasting)', 'Fluoride Plasma', 70.00),
  ('Glucose (Post Prandial)', 'Fluoride Plasma', 70.00),
  ('Glucose (Random)', 'Fluoride Plasma', 70.00),
  ('Glucose Challenge Test 2 hr 75g Glucose (GCT)', 'Fluoride Plasma', 100.00),
  ('Glucose Tolerance Test (GTT) - 3 Sample', 'Fluoride Plasma', 400.00),
  ('Gram''s Stain (Urine, Sputum, Stool)', 'Urine/Sputum/Stool in Sterile Leak Proof Container', 350.00),
  ('HbA1c (Glycosylated Hemoglobin)', 'EDTA Whole Blood', 500.00),
  ('Hemoglobin (Hb)', 'EDTA Whole Blood', 150.00),
  ('Hemoglobin HPLC/ Electrophoresis', 'EDTA Whole Blood', 700.00),
  ('Hepatitis B Surface Antigen (HBsAg)', 'Serum', 350.00),
  ('Hepatitis C Virus (HCV)', 'Serum', 350.00),
  ('High-Sensitivity C-Reactive Protein (Hs-CRP)', 'Serum', 800.00),
  ('HIV I&II (Card Test)', 'Serum', 350.00),
  ('HLAB 27', 'EDTA Whole Blood', 1200.00),
  ('Insulin (Fasting)', 'Serum', 750.00),
  ('Insulin (Post Prandial)', 'Serum', 750.00),
  ('Insulin (Random)', 'Serum', 750.00),
  ('Iron', 'Serum', 300.00),
  ('Iron Studies', 'Serum', 700.00),
  ('Kidney Function Test (KFT)', 'Serum', 500.00),
  ('Lipase', 'Serum', 700.00),
  ('Lipid Profile', 'Serum', 500.00),
  ('Liver Function Test (LFT)', 'Serum', 700.00),
  ('Luteinizing Hormone (LH)', 'Serum', 500.00),
  ('Magnesium', 'Serum', 400.00),
  ('Malaria Parasite (MPICT Card Test)', 'EDTA Whole Blood', 350.00),
  ('MicroAlbumin Creatinine Ratio (Urine)', 'Urine in Sterile Leak Proof Container', 900.00),
  ('Occult Blood (Stool)', 'Stool in Sterile Leak Proof Container', 350.00),
  ('Parathyroid Hormone (PTH)', 'Serum', 1500.00),
  ('Peripheral Blood Smear (PBS / GBP)', 'EDTA Whole Blood', 300.00),
  ('Prolactin (PRL)', 'Serum', 500.00),
  ('Prothrombin Time and International Normalized Ratio (PT/INR)', 'Citrated Plasma', 400.00),
  ('Renal Function Test (RFT)', 'Serum', 750.00),
  ('Reticulocyte Count', 'EDTA Whole Blood', 300.00),
  ('Rheumatoid Factor (RA- Quantitative)', 'Serum', 450.00),
  ('Scrub Typhus IgG IgM', 'Serum', 900.00),
  ('Semen Examination', 'Semen in Sterile Leak Proof Container', 500.00),
  ('Serum Albumin', 'Serum', 200.00),
  ('Serum Alkaline Phosphatase', 'Serum', 200.00),
  ('Serum Amylase', 'Serum', 450.00),
  ('Serum Bilirubin (Direct)', 'Serum', 150.00),
  ('Serum Bilirubin (Total)', 'Serum', 150.00),
  ('Serum Calcium', 'Serum', 120.00),
  ('Serum Chloride', 'Serum', 200.00),
  ('Serum Creatinine', 'Serum', 150.00),
  ('Serum Electrolytes Profile', 'Serum', 450.00),
  ('Serum IgE', 'Serum', 900.00),
  ('Serum Lactate Dehydrogenase (LDH)', 'Serum', 350.00),
  ('Serum Phosphorus (Po4)', 'Serum', 200.00),
  ('Serum Potassium', 'Serum', 200.00),
  ('Serum Protein', 'Serum', 200.00),
  ('Serum Sodium', 'Serum', 200.00),
  ('Serum Thyroxine (T4)', 'Serum', 200.00),
  ('Serum Triiodothyronine (T3)', 'Serum', 200.00),
  ('Serum Urea', 'Serum', 150.00),
  ('Serum Uric Acid', 'Serum', 200.00),
  ('Stool Routine Examination', 'Stool in Sterile Leak Proof Container', 200.00),
  ('Thyroid Function Test (TFT)', 'Serum', 500.00),
  ('Thyroid-Stimulating Hormone (TSH)', 'Serum', 250.00),
  ('Total Cholesterol', 'Serum', 100.00),
  ('Total PSA', 'Serum', 700.00),
  ('Triglycerides (TG)', 'Serum', 100.00),
  ('Typhidot IgG IgM', 'Serum', 900.00),
  ('Urine for Microalbumin', 'Urine in Sterile Leak Proof Container', 600.00),
  ('Urine Protein Creatinine Ratio (UPCR)', 'Urine in Sterile Leak Proof Container', 800.00),
  ('Urine Routine Examination', 'Urine in Sterile Leak Proof Container', 150.00),
  ('VDRL', 'Serum', 300.00),
  ('Viral Marker (Qualitative)', 'Serum', 900.00),
  ('Viral Marker (Quantitative)', 'Serum', 1250.00),
  ('Vitamin B12', 'Serum', 1000.00),
  ('Widal (Slide Method)', 'Serum', 350.00),
  ('17 OH Progesterone Serum', 'Serum', 1400.00),
  ('24 hours Urine Cortisol', 'Urine in Sterile Leak Proof Container', 1300.00),
  ('Acid Fast Bacilli Smear (AFB)', 'Urine in Sterile Leak Proof Container', 400.00),
  ('Acid Fast Bacilli Sputum (AFB)', 'Sputum in Sterile Leak Proof Container', 450.00),
  ('Adenosine Deaminase (ADA)', 'Serum', 800.00),
  ('Adrenocorticotropic Hormone (ACTH)', 'EDTA Whole Blood', 1800.00),
  ('Alfa Fetoprotein (AFP)', 'Serum', 750.00),
  ('Ammonia', 'Sodium Heparin Vacutainer/ EDTA Whole Blood', 1200.00),
  ('Anti Cardiolipin IgG IgM', 'Serum', 1600.00),
  ('Anti Hepatitis B Core Antibody (AHBC) IgM', 'Serum', 1000.00),
  ('Anti Hepatitis B Envelope Antibody (AHBE)', 'Serum', 1000.00),
  ('Anti Hepatitis B Surface Antibody (AHBS) Titre', 'Serum', 1000.00),
  ('Anti Nuclear Antibody (ANA)', 'Serum', 800.00),
  ('Anti Phospholipid (APL) IgG', 'Serum', 900.00),
  ('Anti Phospholipid (APL) IgM', 'Serum', 900.00),
  ('Anti Thyroglobulin Antibody (ATG)', 'Serum', 1100.00),
  ('Anti-HAV IgG', 'Serum', 900.00),
  ('Anti-HAV IgM', 'Serum', 900.00),
  ('Anti-Mullerian Hormone (AMH)', 'Serum', 1700.00),
  ('Antinuclear Antibody (ANA-Bolt)', 'Serum', 3000.00),
  ('Apolipoprotein A-1 (Apo A-1)', 'Serum', 500.00),
  ('Apolipoprotein B (ApoB)', 'Serum', 500.00),
  ('Beta 2 Glycoprotein 1 (IgG)', 'Serum', 1200.00),
  ('Beta 2 Glycoprotein 1 (IgM)', 'Serum', 1200.00),
  ('Bicarbonate', 'Serum', 600.00),
  ('Bile Acid', 'Serum', 1400.00),
  ('Blood Culture (With Bottle)', 'Inoculated Bactec Bottle', 1350.00),
  ('C3 Complement', 'Serum', 700.00),
  ('C4 Complement', 'Serum', 700.00),
  ('CA 125', 'Serum', 1200.00),
  ('CA 15.3', 'Serum', 1200.00),
  ('CA 19.9', 'Serum', 1200.00),
  ('CA 72.4', 'Serum', 2600.00),
  ('Calcitonin', 'Serum', 2700.00),
  ('Carcinoembryonic Antigen (CEA)', 'Serum', 600.00),
  ('Cardiac Risk Marker', 'Serum', 1300.00),
  ('CBNAAT (Sputum)', 'Sputum in Sterile Leak Proof Container', 2500.00),
  ('Ceruloplasmin', 'Serum', 950.00),
  ('Chikungunya Combo Rapid Test', 'Serum', 1500.00),
  ('CMV Avidity test', 'Serum', 1500.00),
  ('Creatine Phospho Kinase (CPK-Total)', 'Serum', 500.00),
  ('Creatine Phospho Kinase MB (CK-MB)', 'Serum', 800.00),
  ('D-Dimer', 'Citrated Plasma', 1500.00),
  ('Dehydroepiandrosterone - Sulfate (DHEA)', 'Serum', 1200.00),
  ('Di Hydro Testosterone (DHT)', 'Serum', 2000.00),
  ('Direct Coomb''s Test', 'EDTA Whole Blood', 800.00),
  ('Double Marker (First Trimester)', 'Serum', 2000.00),
  ('Drug Of Abuse Panel (Rapid)', 'Urine in Sterile Leak Proof Container', 1500.00),
  ('Estradiol', 'Serum', 600.00),
  ('Fibrinogen (Coagulation Factor I)', 'Citrated Plasma', 1800.00),
  ('Folic Acid', 'Serum', 800.00),
  ('Free Beta HCG', 'Serum', 1000.00),
  ('Free PSA', 'Serum', 900.00),
  ('Fructosamine', 'Serum', 1500.00),
  ('Gamma Glutamyl Transferase (GGT)', 'Serum', 380.00),
  ('Glucose-6-Phosphate Dehydrogenase (G6PD)', 'EDTA Whole Blood', 1000.00),
  ('Helicobacter Pylori Antigen Detection by Stool', 'Stool in Sterile Leak Proof Container', 1600.00),
  ('Hepatitis B Envelope Antigen (HBeAg)', 'Serum', 900.00),
  ('HOMA-IR (Using Insulin)', 'Serum, Fluride Plasma', 1200.00),
  ('Homocysteine', 'Serum', 1200.00),
  ('Human Growth Hormone (HGH)', 'Serum', 650.00),
  ('iCalcium', 'Serum', 750.00),
  ('Indirect Coomb''s Test', 'Serum', 800.00),
  ('Lactate', 'Fluoride Plasma', 900.00),
  ('Leptospira IgG IgM (Rapid)', 'Serum', 800.00),
  ('Lipoprotein (A)', 'Serum', 950.00),
  ('Lithium', 'Serum', 500.00),
  ('Lupus Anticoagulant (DRVVT)', 'Citrated Plasma', 1700.00),
  ('Malaria Antigen Detection', 'EDTA Whole Blood', 700.00),
  ('Malaria Parasite (MPICT QBC)', 'EDTA Whole Blood', 600.00),
  ('Mantoux Test', 'NA', 500.00),
  ('Microfilarial Parasite (MF Card Test)', 'Serum', 1500.00),
  ('Myoglobin Serum', 'Serum', 2600.00),
  ('N-Terminal Pro-B-Type Natriuretic Peptide (NT-proBNP)', 'Serum', 3500.00),
  ('Noninvasive Prenatal Testing (NIPT/NIPS)', '10 ml of Maternal Blood in Streck Tube', 13000.00),
  ('Osmolality (Serum)', 'Serum, Fluride Plasma', 1000.00),
  ('Osmolality (Urine)', 'Urine in Sterile Leak Proof Container', 1000.00),
  ('Osmotic Fragility Test', 'Sodium Heparin Vacutainer', 1200.00),
  ('Procalcitonin', 'Serum', 2000.00),
  ('Progesterone', 'Serum', 650.00),
  ('Protein Electrophoresis', 'Serum', 1000.00),
  ('Quadruple Marker (Second Trimester)', 'Serum', 3000.00),
  ('QuantiFERON TB GOLD (Interferon Gamma Release Assay)', 'Sodium Heparin Vacutainer', 1800.00),
  ('Rubella IgG', 'Serum', 650.00),
  ('Rubella IgM', 'Serum', 650.00),
  ('Rubella Virus Avidity', 'Serum', 1500.00),
  ('Serum Cholinesterase', 'Serum', 2000.00),
  ('Serum Copper', 'Serum', 300.00),
  ('Serum Cortisol', 'Serum', 650.00),
  ('Serum IgA', 'Serum', 900.00),
  ('Serum IgG', 'Serum', 900.00),
  ('Serum IgM', 'Serum', 900.00),
  ('Serum Zinc', 'Serum', 900.00),
  ('Sputum Culture & Sensitivity', 'Sputum in Sterile Leak Proof Container', 650.00),
  ('Sputum Routine', 'Sputum in Sterile Leak Proof Container', 450.00),
  ('Stool Culture & Sensitivity', 'Stool in Sterile Leak Proof Container', 500.00),
  ('Stool Reducing Substances', 'Stool in Sterile Leak Proof Container', 400.00),
  ('Swab Culture & Sensitivity', 'Swab in Sterile Leak Proof Container', 900.00),
  ('Testosterone (Free)', 'Serum', 1100.00),
  ('Testosterone (Total)', 'Serum', 600.00),
  ('Throat Culture & Sensitivity', 'Throat Swab in Sterile Leak Proof Container', 1100.00),
  ('Thyroglobulin (TG)', 'Serum', 1400.00),
  ('Torch Profile 8 Panel', 'Serum', 1700.00),
  ('Total Iron Binding Capacity (TIBC)', 'Serum', 450.00),
  ('Toxo IgG', 'Serum', 700.00),
  ('Toxo IgM', 'Serum', 700.00),
  ('Treponema Pallidum Hemagglutination Assay (TPHA)', 'Serum', 1400.00),
  ('Triple Marker (Second Trimester)', 'Serum', 3000.00),
  ('Troponin I', 'Serum', 1500.00),
  ('Troponin T', 'EDTA Whole Blood', 1500.00),
  ('Unconjugated Estriol (E3)', 'Serum', 1100.00),
  ('Urinary Electrolytes', 'Urine in Sterile Leak Proof Container', 600.00),
  ('Urine Bile Pigment', 'Urine in Sterile Leak Proof Container', 150.00),
  ('Urine Bile Salt', 'Urine in Sterile Leak Proof Container', 150.00),
  ('Urine Culture & Sensitivity', 'Urine in Sterile Leak Proof Container', 550.00),
  ('Urine for Acid Fast Bacilli (AFB)', 'Urine in Sterile Leak Proof Container', 550.00),
  ('Urine for Chyle', 'Urine in Sterile Leak Proof Container', 750.00),
  ('Urine for Ketone', 'Urine in Sterile Leak Proof Container', 450.00),
  ('Urine for Protein', 'Urine in Sterile Leak Proof Container', 450.00),
  ('Urine Pregnancy Test (UPT)', 'Urine in Sterile Leak Proof Container', 200.00),
  ('Urine Sugar (Fasting)', 'Urine in Sterile Leak Proof Container', 100.00),
  ('Urine Sugar (Post Prandial)', 'Urine in Sterile Leak Proof Container', 100.00),
  ('Urine Sugar (Random)', 'Urine in Sterile Leak Proof Container', 100.00),
  ('Valproic Acid', 'Serum', 800.00),
  ('Weil Felix', 'Serum', 1300.00),
  ('Widal (Tube Method) 24 Hours', 'Serum', 350.00)
) as v(name, category, price)
where not exists (
  select 1 from individual_tests t where t.name = v.name
);
